### ISSUE TITLE
Bloom filter example in the README flips false negatives and false positives

### ISSUE THREAD

**Issue by vlmutolo** [tverghis/flit#5]
## Current README:
```rust
filter.add(&"Hello, world!");
assert_eq!(filter.might_contain(&"Hello, world!"), true); // probably true
assert_eq!(filter.might_contain(&"Dogs are cool!"), false); // definitely false!
```
## Suggested README:
(Difference is in the comments.)
```rust
filter.add(&"Hello, world!");
assert_eq!(filter.might_contain(&"Hello, world!"), true); // definitely true
assert_eq!(filter.might_contain(&"Dogs are cool!"), false); // probably false
```

## Explanation
The promises of a Bloom filter are that:

1. an element in the filter will always return `True`, and
2. an element not in the filter will probably return `False`.

I think you accidentally flipped it in the README.

**Comment by tverghis** [comment]
Hi @vlmutolo! Thanks for the comment.

If an element exists in a bloom filter, the data structure can only say that it might exist. If it does not exist, the data structure can say with 100% confidence that it does not. I think the current example is correct.

Here's a good reference: https://llimllib.github.io/bloomfilter-tutorial/

I'm going to close this, but feel free to let me know if there is still need for discussion. Thanks!

**Comment by vlmutolo** [comment]
I just took several round trips between various resources and this issue page. For a second it seemed like I was going insane, but I think I figured out the source of confusion.

Boom filters have no false negatives but some false positives. So, like you said, if the filter returns true for an unknown test, that true could be a false positive and is only probabilistic. And if it returns false, it definitely should be false.

But in your example, you're not asking "given that the filter returns `false`, is it really `false`?". You're instead asking "given that *it's actually `false`*, will the filter return `false`"? Same thing for `true`. That flips the question around, and I think my suggestion is correct.

Another way of thinking about it: if you insert element `x`, all the bits for element `x` will be 1. When you go to check again for element `x`, those bits will still be 1, and it will definitely return `true`. If you instead check for a different element `y`, there's a chance that `y` hashes to the same bits as `x`, in which case a check for `y` could return `true` instead of `false` as it should.

That said, maybe I really am going insane and none of this makes sense. :man_shrugging:

**Comment by tverghis** [comment]
> Another way of thinking about it: if you insert element x, all the bits for element x will be 1. When you go to check again for element x, those bits will still be 1, and it will definitely return true.

I think there's a mistake here: The bloom filter cannot say that this is **definitely** true. It _will_ return true, but it doesn't mean that x definitely exists. It just means that "something hashed to the same thing that x also hashes to". That is, if you insert element x, and then check for x, the answer is still not definitive.

**Comment by vlmutolo** [comment]
Completely agree. When I read the example comment, I interpreted it as “this will probably return True”, rather than “the `true` that this returns is probably correct.

Plus, I think it’s a bit confusing because, in the example, there’s nothing probabilistic about the `true` example. There’s a 100% chance the filter returns true and 100% chance that true is correct. 

Plus, for the `false` example, there are certain strings other than `Dogs are cool!` that will actually produce a `true` value there. So that is, in a sense, probabilistic, if you consider the string you choose probabilistic. 

Maybe the example could be improved by adding a dev dependency on rand and testing a random number instead of an element known to be in the set.
